//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using static System.Net.Mime.MediaTypeNames;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string ID { get; set; }
        public string StaffID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        public override string ToString()
        {
            string str = (ID + StaffID + Customer.fullname + BillDate.ToString() + Discount.ToString() + Total.ToString());
            return Regex.Replace(str, @"s", "").ToLower();
        }
    }
}
