//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodUpgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportListing
    {
        public string ID { get; set; }
        public string ImportID { get; set; }
        public string ProvidersID { get; set; }
        public string IngredientID { get; set; }
    
        public virtual Import Import { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
