//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Bill>();
                db.CreateTable<Customer>();
                db.CreateTable<Import>();
                db.CreateTable<Ingredient>();
                db.CreateTable<Orders>();
                db.CreateTable<Product>();
                db.CreateTable<Providers>();
                db.CreateTable<Staff>();
            }
        }
    }
    public partial class Bill
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(15)]
        public String StaffID { get; set; }
        
        [MaxLength(15)]
        public String CustomerID { get; set; }
        
        public DateTime? BillDate { get; set; }
        
        public Int32? Discount { get; set; }
        
        public Int32? Total { get; set; }
        
    }
    
    public partial class Customer
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(15)]
        public String fullname { get; set; }
        
        [MaxLength(10)]
        public String Sex { get; set; }
        
        [MaxLength(14)]
        public String Phone { get; set; }
        
        public Int32? Total { get; set; }
        
        [MaxLength(15)]
        public String CustomerRank { get; set; }
        
        [MaxLength(80)]
        public String CustomerAddress { get; set; }
        
    }
    
    public partial class Import
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(15)]
        public String IngredientID { get; set; }
        
        [MaxLength(15)]
        public String ProvidersID { get; set; }
        
        public DateTime? ImportDate { get; set; }
        
    }
    
    public partial class Ingredient
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(40)]
        public String IngredientName { get; set; }
        
        [MaxLength(30)]
        public String IngredientType { get; set; }
        
        public Int32? Price { get; set; }
        
        [MaxLength(20)]
        public String Unit { get; set; }
        
        public Decimal? Remaining { get; set; }
        
        [MaxLength(80)]
        public String Descript { get; set; }
        
        [MaxLength(15)]
        public String Avatar { get; set; }
        
    }
    
    public partial class Orders
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(15)]
        public String BillID { get; set; }
        
        [MaxLength(15)]
        public String ProductID { get; set; }
        
        public Int32? sell { get; set; }
        
        public Int32? price { get; set; }
        
        public Int32? Discount { get; set; }
        
        public Int32? Total { get; set; }
        
    }
    
    public partial class Product
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(40)]
        public String ProductName { get; set; }
        
        [MaxLength(30)]
        public String ProductType { get; set; }
        
        public Int32? Price { get; set; }
        
        public Int32? Remaining { get; set; }
        
        [MaxLength(80)]
        public String Descript { get; set; }
        
        [MaxLength(15)]
        public String Avatar { get; set; }
        
    }
    
    public partial class Providers
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(40)]
        public String ProviderName { get; set; }
        
        public DateTime? DayStart { get; set; }
        
        public DateTime? DayEnd { get; set; }
        
        [MaxLength(80)]
        public String Descript { get; set; }
        
    }
    
    public partial class Staff
    {
        [PrimaryKey]
        [MaxLength(15)]
        public String ID { get; set; }
        
        [MaxLength(50)]
        public String fullname { get; set; }
        
        [MaxLength(20)]
        public String accessRight { get; set; }
        
        [MaxLength(30)]
        public String username { get; set; }
        
        [MaxLength(30)]
        public String pass { get; set; }
        
        [MaxLength(10)]
        public String sex { get; set; }
        
        public DateTime? DOB { get; set; }
        
        [MaxLength(14)]
        public String phone { get; set; }
        
        [MaxLength(40)]
        public String mail { get; set; }
        
        [MaxLength(100)]
        public String addr { get; set; }
        
    }
    
}
